# Generated by Django 6.0.5 on 2026-05-10 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_nutrients_options_food_consumed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FOOD_CONSUMED',
            new_name='FoodConsumed',
        ),
        migrations.AlterModelOptions(
            name='foodconsumed',
            options={'verbose_name': 'Food Consumed', 'verbose_name_plural': 'Foods Consumed'},
        ),
    ]
